### ISSUE TITLE
Bubble up contacts with unread messages

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1254] opened 2018-10-22 08:55 UTC
I frequently miss new one-on-one messages, as my contact list is pretty long, and the 'unread message count' indicator is "below the fold", using the default 'any' filter. Switching to the 'unread' filter fixes the issue, but doesn't let me see my online users. I'd love for contact list entries that have unread messages to move up the contact list UI thingy.

A suggestion that JC made was to create an "unread messages" pseudo group. I'd be happy with that.

**Comment by jcbrand** [comment] 2018-10-22 12:46
Duplicate of #1253

**Closed by jcbrand** 2018-10-22 12:46 UTC
