### ISSUE TITLE
No error message when trying to join a MUC room with a nickname already in use.

### ISSUE THREAD

**Issue by joudinet** [conversejs/converse.js#1840] opened 2020-01-23 14:20 UTC
**Describe the bug**
Before version 6.0.0, if a client tries to join a MUC room using a nickname already in use, she got an error message and she was invited to choose a different nickname. Now, this message does not show up, so the user has to guess the reason why she's still seeing the chatroom form instead of the room.

**To Reproduce**
1. Go to the page with conversejs
2. Join the room with a nickname
3. Open the same webpage and try to join the the room with the same nickname
4. See no error message

**Expected behavior**
A message saying the nickname is already in use, and you have to choose a different nickname to join the room.

**Environment (please complete the following information):**
 - Desktop and Mobile
 - Browser [Chrome and Firefox]
 - Converse.js version [6.0.0]

**Comment by tanglinhai** [comment] 2020-03-09 08:40
I have the same problem. My solution is to get the list on the right and judge whether it exists

**Comment by mwild1** [comment] 2020-11-11 15:24
I think this may be a duplicate of #2277 (though this one was filed first).

**Comment by jcbrand** [comment] 2020-11-18 09:59
Thanks, closing this one in favour of #2277

**Closed by jcbrand** 2020-11-18 09:59 UTC
Labels: bug
