### ISSUE TITLE
ERROR: 'npm run dev' on windows 10

### ISSUE THREAD

**Issue by m-prati** [conversejs/converse.js#2050] opened 2020-05-29 11:04 UTC
I'm trying to make a dist in Windows 10 with npm, but I've got warning and errors concerning translation:

```
WARNING in ./locale/af/LC_MESSAGES/converse.po 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> # Afrikaans translations for Converse.js package.
| # Copyright (C) 2013 Jan-Carel Brand
| # This file is distributed under the same license as the Converse.js package.
 @ ./locale lazy ^\.\/.*\/LC_MESSAGES\/converse\.po$ namespace object ./af/LC_MESSAGES/converse.po
 @ ./src/headless/i18n.js
 @ ./src/converse-bookmark-views.js
 @ ./src/converse.js
 @ ./src/entry.js
```

```
ERROR in ./src/headless/templates/field.html
Module not found: Error: Can't resolve 'D:progettiProvaopenfireconverse.js
ode_moduleslodashescape.js' in 'D:\progettiProva\openfire\converse.js\src\headless\templates'
 @ ./src/headless/templates/field.html 1:16-94
 @ ./src/headless/utils/form.js
 @ ./src/converse-register.js
 @ ./src/converse.js
 @ ./src/entry.js
```

In a cmd console I typed: `npm run dev`

Can somebody help me?

**Comment by jcbrand** [comment] 2020-06-03 08:44
Duplicate of #2043, please see what I wrote there.

**Closed by jcbrand** 2020-06-03 08:44 UTC
