### ISSUE TITLE
Show/Hide Offline Users

### ISSUE THREAD

**Issue by deleolajide** [conversejs/converse.js#1223] opened 2018-09-25 09:57 UTC
There should be an option to toggle showing or hiding the offline users right in the front of the users list, even when filtering by user name or group. Showing online contacts should be the default.

Users can add more contacts through the add contact button, which is also the tool to search for people they don't have on their list.

This also seems to be the standard for most chat programs.

This issue was forwarded from [here](https://github.com/igniterealtime/Pade/issues/56)

**Comment by jcbrand** [comment] 2018-09-26 08:01
> Showing online contacts should be the default.

I don't agree. If you have a small contacts roster and all of them are offline, then you don't see any contacts and might not understand why. It's IMO better to see all contacts and then filter, then to see no contacts (or fewer contacts) and not understand why.

> There should be an option to toggle showing or hiding the offline users right

Looks to me like this requirement is a duplicate of #1089 
I'll close in favor of that ticket.

**Closed by jcbrand** 2018-09-26 08:01 UTC
