### ISSUE TITLE
MAM archive not fetched due to "empty" messages

### ISSUE THREAD

**Issue by dickverweij** [conversejs/converse.js#1621] opened 2019-06-26 15:35 UTC
We have an ejabberd server with mam configured. I can see all mam messages stored there. But when using it with converse.js it does not show (all of) the archive messages. 

We investigated further it seems that converse is loading 50 messages, but all of them are "empty", this prevents further loading of old Mam messages.

When looking in the database there are a lot of empty messages stored: 
We dont know what causes these empty messages (are these presence messages of some kind?)

example:
(xxx- and yyy- ed the reald jids)
`<message xml:lang='en' to='xxxxxxxxx/converse.js-100946682' from='yyyyyyyyyy/converse.js-118239409' type='chat' id='f1b4dc5b-84dc-412e-b4d7-6b8b23f681c0' xmlns='jabber:client'><received xmlns='urn:xmpp:receipts' id='83eccf3c-a64a-4470-a71e-995f4ffe0feb'/><store xmlns='urn:xmpp:hints'/></message>`

these messages appear to have no body.

I can see that the script is loading these messages, neither of them has a body so resulting in a empy chat window.

**Comment by jcbrand** [comment] 2019-06-28 14:07
I think this is basically a duplicate of #1548

**Comment by dickverweij** [comment] 2019-07-01 09:22
Ok, any clue why those "empty messages" occur in the first place?

**Comment by jcbrand** [comment] 2019-07-01 09:38
I guess your XMPP server stores chat state notifications and perhaps other similar "empty" messages in the MAM archive.

https://xmpp.org/extensions/xep-0085.html

**Comment by jcbrand** [comment] 2019-09-17 08:07
Should be fixed as part of the fix for #1548

**Closed** 2019-09-17 08:07 UTC
Labels: bug
