### ISSUE TITLE
Configuration: "allow_non_roster_messaging: true" -> incomplete chat window

### ISSUE THREAD

**Issue by MotoGP-Fan** [conversejs/converse.js#1221] opened 2018-09-24 11:12 UTC
Converse release: 4.0.1
Prosody 0.10.2 on Debian 9

If "allow_non_roster_messaging" is set to "true" (default=false) the chat window will not appear in usual style ->text input not possible.
If you want to test this by yourself don't forget to clear browser cache and reload site after changing the configuration option. See pic:

![webchat_nok_pixel](https://user-images.githubusercontent.com/30147533/45948693-4a5a6480-bff9-11e8-80e6-16dfe15be3d8.png)

**Comment by sicherha** [comment] 2018-09-25 09:04
I can reproduce this behaviour: the input area goes missing when OMEMO support is enabled (i.e. when `libsignal-protocol.js` is loaded). With OMEMO disabled, the input widget re-appears.

**Comment by jcbrand** [comment] 2018-10-05 15:34
@MotoGP-Fan and @sicherha: I'm not able to reproduce this bug. Can you please check again whether it's fixed with the 4.0.2 release? Make sure the browser's cache is cleared.

**Comment by jcbrand** [comment] 2018-10-10 13:52
@sicherha Please set `debug: true` when calling `converse.initialize`, or use https://conversejs.org/fullscreen_debug.html

Then in your browser console, enable `verbose` logging. Then reproduce the problem, copy the entire log output and paste it here.

Then I can try and see what the problem is.

**Comment by sicherha** [comment] 2018-10-10 15:22
Log sent via email.

**Comment by jcbrand** [comment] 2018-10-10 18:19
@sicherha I think I found and fixed the bug. You were using `allow_non_contact_requests: true` right? This caused an orange headlines box to be created for an OMEMO headline message which in turn prevented a normal chat to be created.

Are you using the CDN or do you have a dev environment set up for Converse?

**Comment by sicherha** [comment] 2018-10-10 22:31
Yes, I was using `allow_non_contact_requests: true`. Our deployment is hosted locally and doesn't make use of the CDN.

I can confirm that your patch appears to fix the issue for me. Thanks for the quick and competent response! :+1:

**Comment by jcbrand** [comment] 2018-10-11 03:09
Cool, thanks for the confirmation

**Closed** 2018-10-11 03:08 UTC
Labels: bug
