### ISSUE TITLE
Failed to execute 'setItem' on 'Storage'

### ISSUE THREAD

**Issue by member7me** [conversejs/converse.js#2456] opened 2021-04-13 19:35 UTC
Hello.
Chrome 89.0.4389.114.
My localStorage limit is 5000 KBs - http://jsfiddle.net/53xcc4LL/
Received error in browser
![error](https://user-images.githubusercontent.com/66087479/114610352-76698e00-9ca8-11eb-8355-57d08d59c13e.png)
Seems like conversejs doesn't clear localStorage in browser (such a feeling)
It clears only manually through `window.localStorage.clear()` in console.
Maybe somewhere it was forgotten in sources?

**Comment by jcbrand** [comment] 2021-04-14 07:41
Yes, your localStorage is full. 

This is a duplicate of #2425

**Closed by jcbrand** 2021-04-14 07:41 UTC
