### ISSUE TITLE
In overlayed mode the input form icons scroll with the page

### ISSUE THREAD

**Issue by rmcsharry** [conversejs/converse.js#3133] opened 2023-02-05 07:33 UTC
**Describe the bug**
In overlayed mode, scrolling causes the input icons on the login form to scroll outside the inputs

**To Reproduce**
1. Go to converse.js
2. Click on Toggle to open the chat
3. Move mouse to main page and scroll
4. See icons move on the chat window form

(notice that they also scroll off the inputs, but stay on the form, if you ONLY scroll the form itself and not just the page)

**Expected behavior**
Icons should stay inside the inputs

**Video**

https://user-images.githubusercontent.com/1156100/216807126-bbf09c6c-7d3e-499f-b67b-900b8e1249d2.mp4

**Environment (please complete the following information):**
 - Desktop with overlayed mode
 - Browser Chrome latest
 - Converse.js 8

**Comment by licaon-kter** [comment] 2023-02-05 08:15
Latest Converse is version 10.x did you test it too?

**Comment by love-sonkar** [comment] 2023-09-25 16:56
this issue is not fixed in latest version

**Comment by jcbrand** [comment] 2023-09-29 05:43
@love-sonkar What kind of icons are those? I don't see any icons and it doesn't look to me like something that's added by the Converse CSS. Did you add them yourself?

**Comment by love-sonkar** [comment] 2023-09-29 05:51
when you open the chat box in home screen it's overflow and the conversjs logo is not looking good because of the Scrollbar so he wanted to fix the Scrollbar

**Comment by jcbrand** [comment] 2023-09-29 05:54
He is referring to ` input icons on the login form to scroll outside the inputs`. I don't know what those "input icons" are. I don't wee them.

**Comment by love-sonkar** [comment] 2023-09-29 05:59
ohh okay now i can understand clearly this issue so he is trying to say those 2 icon in right side which is scroll when user scroll the page 

see the video when he scroll the 2 icons overflow in right side and this issue is fixed

**Comment by jcbrand** [comment] 2023-09-29 07:29
Yeah, but I'm wondering what those icons are and where they come from. I don't see them when I use Converse.

**Comment by love-sonkar** [comment] 2023-09-29 07:31
The issue is fixed in version 10 that's why we can't see

**Comment by jcbrand** [comment] 2023-09-29 14:24
Ok thanks, then I'll close this ticket.

**Closed by jcbrand** 2023-09-29 14:24 UTC
