### ISSUE TITLE
Conversation History is no longer available

### ISSUE THREAD

**Issue by ulsaramana** [conversejs/converse.js#1739] opened 2019-10-03 10:32 UTC
Hi,
We have a big team who is using the converse app since 3 months, 
All of sudden from last before week the conversation Chat history is not showing any-more all the users. 
We have very important conversation from our users, which needed by our users please advise? 
The saved Contacts also not shows up properly. when we logged out and logged in they gone.

Browser [e.g. Chrome, Firefox]
Converse.js version [e.g. 4.2.0]

Thanks
Ramana

**Comment by jcbrand** [comment] 2019-10-04 16:30
Is this perhaps a duplicate of #1735?

**Comment by Echolon** [comment] 2021-04-02 22:46
Hi @ulsaramana,

I will close this. If there is further input, please let us know!

**Closed** 2021-04-02 22:46 UTC
Labels: Not enough info, duplicate, question
