### ISSUE TITLE
create avatar plugin

### ISSUE THREAD

**Issue by supun19** [conversejs/converse.js#1511] opened 2019-03-26 12:41 UTC
I find  an avatar plugin code from pade extension. when login the avatar not set profile but when click on the profile it show the avatar and when i reload the page the avatar set. Ididnt get any error message. can you give me suggestion to fix this issue

```
// version 0.4.11.1

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
      // AMD. Register as a module called "webmeet"
      define(["converse"], factory);
  } else {
      // Browser globals. If you're not using a module loader such as require.js,
      // then this line below executes. Make sure that your plugin's <script> tag
      // appears after the one from converse.js.
      factory(converse);
  }
}(this, function (converse) {

  // Commonly used utilities and variables can be found under the "env"
  // namespace of the "converse" global.
  var Strophe = converse.env.Strophe,
      $iq = converse.env.$iq,
      $msg = converse.env.$msg,
      $pres = converse.env.$pres,
      $build = converse.env.$build,
      b64_sha1 = converse.env.b64_sha1,
      _ = converse.env._,
      Backbone = converse.env.Backbone,
      moment = converse.env.moment;
   var _converse = null;
   

   // The following line registers your plugin.
  converse.plugins.add("avatar", {

      /* Optional dependencies are other plugins which might be
         * overridden or relied upon, and therefore need to be loaded before
         * this plugin. They are called "optional" because they might not be
         * available, in which case any overrides applicable to them will be
         * ignored.
         *
         * NB: These plugins need to have already been loaded via require.js.
         *
         * It's possible to make optional dependencies non-optional.
         * If the setting "strict_plugin_dependencies" is set to true,
         * an error will be raised if the plugin is not found.
         */
      'dependencies': [],

      /* Converse.js's plugin mechanism will call the initialize
       * method on any plugin (if it exists) as soon as the plugin has
       * been loaded.
       */
      'initialize': function () {
          /* Inside this method, you have access to the private
           * `_converse` object.
           */
          _converse = this._converse;

          

          console.log("webmeet plugin is ready");

          /* Besides `_converse.api.settings.update`, there is also a
           * `_converse.api.promises.add` method, which allows you to
           * add new promises that your plugin is obligated to fulfill.
           *
           * This method takes a string or a list of strings which
           * represent the promise names:
           *
           *      _converse.api.promises.add('myPromise');
           *
           * Your plugin should then, when appropriate, resolve the
           * promise by calling `_converse.api.emit`, which will also
           * emit an event with the same name as the promise.
           * For example:
           *
           *      _converse.api.emit('operationCompleted');
           *
           * Other plugins can then either listen for the event
           * `operationCompleted` like so:
           *
           *      _converse.api.listen.on('operationCompleted', function { ... });
           *
           * or they can wait for the promise to be fulfilled like so:
           *
           *      _converse.api.waitUntil('operationCompleted', function { ... });
           */
      },

      /* If you want to override some function or a Backbone model or
       * view defined elsewhere in converse.js, then you do that under
       * the "overrides" namespace.
       */
      'overrides': {
          /* For example, the private *_converse* object has a
           * method "onConnected". You can override that method as follows:
           */
          'onConnected': function () {
              // Overrides the onConnected method in converse.js

              // Top-level functions in "overrides" are bound to the
              // inner "_converse" object.
              var _converse = this;
              var uPort = _converse.api.settings.get("uport_data");
                var username = Strophe.getNodeFromJid(_converse.connection.jid);

                console.debug("Found uport data", uPort,_converse.connection);

                // only save avatar if user has success with uport
                    var stanza = $iq({type: 'get', to: Strophe.getBareJidFromJid(_converse.connection.jid)}).c('vCard', {xmlns: 'vcard-temp'});

                    _converse.connection.sendIQ(stanza, function(iq) {
                        var vCard = getVCard(iq);
                        console.log('Vcard',vCard)
                       // TODO ipfs address url

                        if (!vCard.url)
                        {
                            vCard.avatar = createAvatar(username)
                            _converse.connection.sendIQ( setVCard(vCard), function(resp)
                            {
                                console.debug("set vcard ok", resp);
                                _converse.__super__.onConnected.apply(this, arguments);

                            }, function(err) {
                                console.error("set vcard error", err);
                                _converse.__super__.onConnected.apply(this, arguments);
                            });
                        }
                        else {
                            _converse.__super__.onConnected.apply(this, arguments);
                        }
                    });
                
              
          },
          MessageView: {
            renderChatMessage: async function renderChatMessage()
                {
                    //console.debug('webmeet - renderChatMessage', this.model.get("fullname"), this.model.getDisplayName(), this.model.vcard.attributes.fullname, this.model);
                    // intercepting email IM

                    if (this.model.vcard)
                    {
                        if (!this.model.get("fullname") && this.model.get("from").indexOf("\\40") > -1)
                        {
                            this.model.vcard.attributes.fullname = Strophe.unescapeNode(this.model.get("from").split("@")[0]);
                        }

                        var nick = this.model.getDisplayName();

                        if (nick && _converse.DEFAULT_IMAGE == this.model.vcard.attributes.image)
                        {
                            var dataUri = createAvatar(nick);
                            var avatar = dataUri.split(";base64,");

                            this.model.vcard.attributes.image = avatar[1];
                            this.model.vcard.attributes.image_type = "image/png";
                            // this.mode.vcard.set({image: avatar[1],image_type:'image/png'});
                            await this.__super__.renderChatMessage.apply(this, arguments);
                        }
                    }
                    await this.__super__.renderChatMessage.apply(this, arguments);
                  }
          },

          /* Override converse.js's XMPPStatus Backbone model so that we can override the
           * function that sends out the presence stanza.
           */
          'XMPPStatus': {
              'sendPresence': function (type, status_message, jid) {
                  // The "_converse" object is available via the __super__
                  // attribute.
                  var _converse = this.__super__._converse;

                  // Custom code can come here ...

                  // You can call the original overridden method, by
                  // accessing it via the __super__ attribute.
                  // When calling it, you need to apply the proper
                  // context as reference by the "this" variable.
                  this.__super__.sendPresence.apply(this, arguments);

                  // Custom code can come here ...
              }
          }
      }
  });
  var getVCard = function(response)
  {
      var response = $(response);
      var name = response.find('vCard FN').text();
      var photo = response.find('vCard PHOTO');

      var avatar = "";

      if (photo.find('BINVAL').text() != "" && photo.find('TYPE').text() != "")
      avatar = 'data:' + photo.find('TYPE').text() + ';base64,' + photo.find('BINVAL').text();

      var family = response.find('vCard N FAMILY') ? response.find('vCard N FAMILY').text() : "";
          var middle = response.find('vCard N MIDDLE') ? response.find('vCard N MIDDLE').text() : "";
      var given = response.find('vCard N GIVEN') ? response.find('vCard N GIVEN').text() : "";

      var nickname = response.find('vCard NICKNAME') ? response.find('vCard NICKNAME').text() : "";

      var email = response.find('vCard EMAIL USERID') ? response.find('vCard EMAIL USERID').text() : "";
      var url = response.find('vCard URL') ? response.find('vCard URL').text() : "";
      var role = response.find('vCard ROLE') ? response.find('vCard ROLE').text() : "";

      var workPhone = "";
      var homePhone = "";
      var workMobile = "";
      var homeMobile = "";

      response.find('vCard TEL').each(function()
      {
          if ($(this).find('VOICE').size() > 0 && $(this).find('WORK').size() > 0)
              workPhone = $(this).find('NUMBER').text();

          if ($(this).find('VOICE').size() > 0 && $(this).find('HOME').size() > 0)
              homePhone = $(this).find('NUMBER').text();

          if ($(this).find('CELL').size() > 0 && $(this).find('WORK').size() > 0)
              workMobile = $(this).find('NUMBER').text();

          if ($(this).find('CELL').size() > 0 && $(this).find('HOME').size() > 0)
              homeMobile = $(this).find('NUMBER').text();
      });

      var street = "";
      var locality = "";
      var region = "";
      var pcode = "";
      var country = "";

      response.find('vCard ADR').each(function()
      {
          if ($(this).find('WORK').size() > 0)
          {
              street = $(this).find('STREET').text();
              locality = $(this).find('LOCALITY').text();
              region = $(this).find('REGION').text();
              pcode = $(this).find('PCODE').text();
              country = $(this).find('CTRY').text();
          }
      });

      var orgName = response.find('vCard ORG ORGNAME') ? response.find('vCard ORG ORGNAME').text() : "";
      var orgUnit = response.find('vCard ORG ORGUNIT') ? response.find('vCard ORG ORGUNIT').text() : "";

      var title = response.find('vCard TITLE') ? response.find('vCard TITLE').text() : "";

      return {name: name, avatar: avatar, family: family, given: given, nickname: nickname, middle: middle, email: email, url: url, homePhone: homePhone, workPhone: workPhone, homeMobile: homeMobile, workMobile: workMobile, street: street, locality: locality, region: region, pcode: pcode, country: country, orgName: orgName, orgUnit: orgUnit, title: title, role: role};
  }

  var setVCard = function(user)
  {
      var avatar = user.avatar.split(";base64,");

      var iq = $iq({to:  _converse.connection.domain, type: 'set'}).c('vCard', {xmlns: 'vcard-temp'})

      .c("FN").t(user.name).up()
      .c("NICKNAME").t(user.nickname).up()
      .c("URL").t(user.url).up()
      .c("ROLE").t(user.role).up()
      .c("EMAIL").c("INTERNET").up().c("PREF").up().c("USERID").t(user.email).up().up()
      .c("PHOTO").c("TYPE").t(avatar[0].substring(5)).up().c("BINVAL").t(avatar[1]).up().up()
      .c("TEL").c("VOICE").up().c("WORK").up().c("NUMBER").t(user.workPhone).up().up()
      .c("ADR").c("WORK").up().c("STREET").t(user.street).up().c("LOCALITY").t(user.locality).up().c("REGION").t(user.region).up().c("PCODE").t(user.pcode).up().c("CTRY").t(user.country).up().up()
/*
      .c("TEL").c("PAGER").up().c("WORK").up().c("NUMBER").up().up()
      .c("TEL").c("CELL").up().c("WORK").up().c("NUMBER").t(user.workMobile).up().up()

      .c("TEL").c("FAX").up().c("WORK").up().c("NUMBER").up().up()
      .c("TEL").c("PAGER").up().c("HOME").up().c("NUMBER").up().up()
      .c("TEL").c("CELL").up().c("HOME").up().c("NUMBER").t(user.homeMobile).up().up()
      .c("TEL").c("VOICE").up().c("HOME").up().c("NUMBER").t(user.homePhone).up().up()
      .c("TEL").c("FAX").up().c("HOME").up().c("NUMBER").up().up()
      .c("URL").t(user.url).up()
      .c("ADR").c("HOME").up().c("STREET").up().c("LOCALITY").up().c("REGION").up().c("PCODE").up().c("CTRY").up().up()
      .c("TITLE").t(user.title).up()
*/
      return iq;
  }
  
}));

```

I have added two function for root script(index.js)

```
function createAvatar(nickname, width, height, font)
{
    console.log('create canvas');
    nickname = nickname.toLowerCase();

    if (avatars[nickname])
    {
        return avatars[nickname];
    }

    if (!width) width = 32;
    if (!height) height = 32;
    if (!font) font = "16px Arial";

    var canvas = document.createElement('canvas');
    canvas.style.display = 'none';
    canvas.width = width;
    canvas.height = height;
    document.body.appendChild(canvas);
    var context = canvas.getContext('2d');
    context.fillStyle = getRandomColor(nickname);
    context.fillRect(0, 0, canvas.width, canvas.height);
    context.font = font;
    context.fillStyle = "#fff";

    var first, last;
    var name = nickname.split(" ");
    var l = name.length - 1;

    if (name && name[0] && name.first != '')
    {
        first = name[0][0];
        last = name[l] && name[l] != '' && l > 0 ? name[l][0] : null;

        if (last) {
            var initials = first + last;
            context.fillText(initials.toUpperCase(), 3, 23);
        } else {
            var initials = first;
            context.fillText(initials.toUpperCase(), 10, 23);
        }
        var data = canvas.toDataURL();
        document.body.removeChild(canvas);
    }

    avatars[nickname] = canvas.toDataURL();
    return avatars[nickname];
}
function getRandomColor(nickname)
{
    if (nickColors[nickname])
    {
        return nickColors[nickname];
    }
    else {
        var letters = '0123456789ABCDEF';
        var color = '#';

        for (var i = 0; i < 6; i++) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        nickColors[nickname] = color;
        return color;
    }
}
```

**Comment by jcbrand** [comment] 2019-03-26 13:58
This is issue is a duplicate of a known bug #1455

**Closed** 2019-03-26 13:58 UTC
