### ISSUE TITLE
Cant open own VCARD (top left in fullscreen mode)

### ISSUE THREAD

**Issue by mightymop** [conversejs/converse.js#1450] opened 2019-02-21 10:20 UTC
Im using the newest version 4.1.1 in fullscreen mode.
When i click on my own VCard Image to open it i get the following error:

VM20:159 Uncaught TypeError: Cannot read property 'get' of undefined
    at o.initialize (<anonymous>:159:643989)
    at o.wrappedOverride (<anonymous>:157:91772)
    at $t (<anonymous>:91:5068)
    at o.t [as initialize] (<anonymous>:91:32844)
    at o.t.View (<anonymous>:75:43872)
    at o.constructor (<anonymous>:83:16713)
    at o [as constructor] (<anonymous>:75:51852)
    at o [as constructor] (<anonymous>:75:51852)
    at new o (<anonymous>:75:51852)
    at o.showProfileModal (<anonymous>:159:532642)

**Comment by jcbrand** [comment] 2019-02-21 16:07
I think this is a duplicate of #1406

**Comment by jcbrand** [comment] 2019-02-26 11:13
@mightymop: Please check whether this still happens with 4.1.2

**Closed** 2019-06-19 07:37 UTC
