### ISSUE TITLE
`Uncaught ReferenceError: can't access lexical declaration 'tp' before initialization`

### ISSUE THREAD

**Issue by paulmenzel** [conversejs/converse.js#3269] opened 2023-09-18 23:17 UTC
Using Node.js v18.16.0 and building commit 70490b397
    
    $ git log --oneline --no-decorate -3
    9d131e958 fullscreen: Use our BOSH
    171f25ee6 fullscreen: Enable Web sockets
    70490b397 Update readme after 10.1.6 release
    $ make dist

the browser console shows the error below:

```
pre-main prep time: 0 ms libsignal-protocol.min.js:1:2566

Uncaught ReferenceError: can't access lexical declaration 'tp' before initialization
    3824 events.js:83
    Webpack 4
        o
        load
        initialize
        <anonymous>
events.js:83:8
    3824 events.js:83
    Webpack 4
        o
        load
        initialize
        <anonym>
```

**Comment by licaon-kter** [comment] 2023-09-19 04:52
This is not https://github.com/conversejs/converse.js/issues/3243 ?

**Comment by paulmenzel** [comment] 2023-09-19 05:28
Unfortunately, I am JavaScript ignorant, but my trace contains `tp` not showing up in the traces in issue https://github.com/conversejs/converse.js/issues/3243.

**Comment by jcbrand** [comment] 2023-09-28 07:26
Closing as dupe of #3243

**Closed by jcbrand** 2023-09-28 07:26 UTC
