### ISSUE TITLE
There is no possibility to read messages of non-roster contacts

### ISSUE THREAD

**Issue by p42ity** [conversejs/converse.js#3163] opened 2023-05-18 11:13 UTC
**Describe the bug**
When setting the option "allow_non_roster_messaging" and receiving messages from non-roster contacts there is no obvious possibility to reach this message.

**To Reproduce**
1. Create a second XMPP account (Account B) and do NOT add this JID to the roster of your normal account (Account A).
2. Login to converseJS with your normal account (Account A).
3. Send an unencrypted message from Account B to Account A using some XMPP client.
4. Converse will show that there is a new message but you cannot reach it using the UI.

**Expected behavior**
There should be a UI element showing the message from an unkown contact.

**Comment by jcbrand** [comment] 2024-12-24 04:10
Duplicate of #1021 and fixed in master.

**Closed by jcbrand** 2024-12-24 04:10 UTC
Labels: UX, UI
