### ISSUE TITLE
Auto login in Firefox does not work 

### ISSUE THREAD

**Issue by open-recipes-app** [conversejs/converse.js#2656] opened 2021-09-17 09:14 UTC
**Describe the bug**
In firefox, although 'this is a trusted device' is checked, login credentials have to be entered everytime

**To Reproduce**
1. Go to 'https://conversejs.org/fullscreen.html'
2. Set Firefox history settings to the ones in the screenshot below
3. Enter 'XMPP Address and password, select 'this is a trusted device' and click login
3. Close firefox browser
4. Open firefox browser and go to 'https://conversejs.org/fullscreen.html'

**Expected behavior**
Conversejs fullscreen should log in automatically

**Screenshots**
![converse](https://user-images.githubusercontent.com/89828026/133757516-57cabcf4-daab-4e2f-bb0a-a4d3cffb8f4f.png)

**Environment (please complete the following information):**
 - Desktop
 - Firefox
 - Converse.js fullscreen latest

**Comment by licaon-kter** [comment] 2021-09-17 09:18
Duplicate of https://github.com/conversejs/converse.js/issues/1449 or https://github.com/conversejs/converse.js/issues/2099 or https://github.com/conversejs/converse.js/issues/2444 ?

**Comment by Echolon** [comment] 2021-09-21 20:43
I will close this as duplicate @jcbrand

**Closed by Echolon** 2021-09-21 20:43 UTC
Labels: bug, fullpage
