### ISSUE TITLE
Bookmarks duplicated

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#2302] opened 2020-10-19 15:35 UTC
**Describe the bug**
Bookmarks are duplicated in the bookmark list. Saving a bookmark appears to persist the duplication, and quadruples them on next load. Etc.

**To Reproduce**
1. Have some bookmarks (without autojoin or `muc_respect_autojoin = false`)
2. Look at list of bookmarks in controlbox
3. Somehow add/edit a bookmark.
4. Log out and try again

**Expected behavior**
Each bookmark listed once.

**Screenshots**
![image](https://user-images.githubusercontent.com/197474/96473057-7759bf80-1231-11eb-8085-a7ee59dc3afa.png)

**Environment (please complete the following information):**
 - Converse.js master
 - Prosody server with mod_bookmarks and mod_conversejs

**Additional context**
`git bisect` points to e49f97472a797c9722e5b51f65c159dc6ca1bb14

**Comment by jcbrand** [comment] 2020-10-19 15:40
I think the issue is improper deduplication of server-pushed bookmark updates (which are now enabled after that change).

**Comment by Zash** [comment] 2020-10-19 15:44
After a bookmark edit there's another push, but this does not seem to introduce any new duplicates.

**Comment by jcbrand** [comment] 2020-10-23 14:23
Should be fixed now @Zash

**Closed** 2020-10-23 14:22 UTC
Labels: bug

**Comment by Zash** [comment] 2020-10-23 18:48
Looks like it is, thanks!
