### ISSUE TITLE
avatar suppor for room list

### ISSUE THREAD

**Issue by supun19** [conversejs/converse.js#1525] opened 2019-04-07 06:10 UTC
I write a custom plugin its will add avatar to the room list. This is the code. i want to know. is it a best way to do it?
```
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
      // AMD. Register as a module called "myplugin"
      define(["converse"], factory);
  } else {
      // Browser globals. If you're not using a module loader such as require.js,
      // then this line below executes. Make sure that your plugin's <script> tag
      // appears after the one from converse.js.
      factory(converse);
  }
}(this, function (converse) {

  // Commonly used utilities and variables can be found under the "env"
  // namespace of the "converse" global.
  var Strophe = converse.env.Strophe,
      $iq = converse.env.$iq,
      $msg = converse.env.$msg,
      $pres = converse.env.$pres,
      $build = converse.env.$build,
      b64_sha1 = converse.env.b64_sha1,
      _ = converse.env._,
      moment = converse.env.moment;
      var _converse;
      const u = converse.env.utils;

  // The following line registers your plugin.
  converse.plugins.add("roomlist", {

   
      'dependencies': ["converse-roomslist","converse-bookmarks"],

   
      'initialize': function () {

          _converse = this._converse;
          _converse.log("The \"myplugin\" plugin is being initialized");

          _converse.api.settings.update({
              'initialize_message': 'Initializing myplugin!'
          });


      },

      /* If you want to override some function or a Backbone model or
       * view defined elsewhere in converse.js, then you do that under
       * the "overrides" namespace.
       */
      'overrides': {
          /* For example, the private *_converse* object has a
           * method "onConnected". You can override that method as follows:
           */
          'onConnected': function () {
              // Overrides the onConnected method in converse.js

              // Top-level functions in "overrides" are bound to the
              // inner "_converse" object.
              var _converse = this;
              
              // You can access the original function being overridden
              // via the __super__ attribute.
              // Make sure to pass on the arguments supplied to this
              // function and also to apply the proper "this" object.
              _converse.__super__.onConnected.apply(this, arguments);

              // Your custom code can come here ...
          },
          RoomsListElementView:{
            render:function(){
              var el = this.__super__.render.apply(this, arguments);
              if(this.model.get('name')){
                if(!this.el.querySelector('channle-icon')){
                  var ele = document.createElement('div');
                  ele.innerHTML = '<img class="channle-icon" src="'+createAvatar(this.model.get('name'))+'"/>';
                  this.el.insertBefore(ele,this.el.children[0])
                } 
              } 
            }
          },
          
          RoomsPanel:{
            events: {
              'click div.controlbox-heading__btn.show-add-muc-modal': 'showAddRoomModal',
            },
            render : function() {
              var el = this.__super__.render.apply(this, arguments);
              var changeBookmarkElementPosition = document.createElement('div')
              changeBookmarkElementPosition.classList.add('list-container');
              changeBookmarkElementPosition.classList.add('bookmarks-list');
              changeBookmarkElementPosition.classList.add('rooms-list-container');
              this.el.insertBefore(changeBookmarkElementPosition,this.el.children[0])
              // console.log('bookmark',this.el.children[3])
              var rootEl = this.el;
              var controlepad =  this.el.querySelector('.controlbox-padded')
              controlepad.removeChild(controlepad.children[2])
              controlepad.removeChild(controlepad.children[0])
              var channelHead = document.createElement('span');
              channelHead.classList.add('w-100');
              channelHead.classList.add('controlbox-heading');
              channelHead.classList.add('ccontrolbox-heading--groupchats');
              channelHead.innerHTML = 'Channels';
              controlepad.insertBefore(channelHead,controlepad.firstChild)
              if(!this.el.querySelector('channle-icon')){
                var ele = document.createElement('div');
                ele.classList.add('controlbox-heading__btn');
                ele.classList.add('show-add-muc-modal');
                ele.innerHTML = '<img class="channle-icon" src="'+createAvatar('+')+'">Add Channel</img>';
                rootEl.children[1].parentNode.insertBefore(ele,rootEl.children[1].nextSibling)
              }
              
              
             
              
          
             return this;
           }
          },
          

          'XMPPStatus': {
              'sendPresence': function (type, status_message, jid) {
                  // The "_converse" object is available via the __super__
                  // attribute.
                  var _converse = this.__super__._converse;

                  // Custom code can come here ...
                  // You can call the original overridden method, by
                  // accessing it via the __super__ attribute.
                  // When calling it, you need to apply the proper
                  // context as reference by the "this" variable.
                  this.__super__.sendPresence.apply(this, arguments);

                  // Custom code can come here ...
              }
          }
      }
  });

  
    
}));
```

**Comment by supun19** [comment] 2019-04-07 06:28
is it suitable to change dom dynamically because some time multiple avatars may add one room

**Comment by muppeth** [comment] 2019-04-11 21:10
I'm not the dev of converse, and didnt test it myself yet but you should definitely push it to community plugins. If there is room for improvements I'm sure someone will join in to help.

**Comment by muppeth** [comment] 2019-04-11 21:42
Getting
`ERROR: User connection callback caused an exception: ReferenceError: createAvatar is not defined`

**Comment by jcbrand** [comment] 2019-04-12 16:17
Closing since this is a duplicate of #1322 

The proper way to add avatar support is to update the [occupant.html](https://github.com/conversejs/converse.js/blob/master/src/templates/occupant.html) template, not to try and manually add DOM elements.

**Closed by jcbrand** 2019-04-12 16:17 UTC
