### ISSUE TITLE
Registration button stop working

### ISSUE THREAD

**Issue by member7me** [conversejs/converse.js#3568] opened 2024-12-19 19:42 UTC
Last version converse.js v10.1.8

Registration button stop working

Previous version works fine.
```
Uncaught TypeError: n._proto._reqToData is not a function
    getRegistrationFields panel.js:96
    _connect_cb panel.js:80
    _onInitialMessage websocket.js:274
    onmessage websocket.js:174
```
``` ERROR: Problem during registration: Strophe.Status is DISCONNECTED```

```Uncaught TypeError: n._proto._reqToData is not a function
    getRegistrationFields panel.js:96
    _connect_cb panel.js:80
    _onInitialMessage websocket.js:274
    onmessage websocket.js:174
    _connect websocket.js:174
    connect connection.js:553
    connect index.js:111
    fetchRegistrationForm panel.js:203
    abortRegistration panel.js:325
    onConnectStatusChanged panel.js:225
    fetchRegistrationForm panel.js:203
    _changeConnectStatus connection.js:1156
    _doDisconnect connection.js:1198
    _checkStreamError websocket.js:127
    _onMessage websocket.js:491
    onmessage websocket.js:286
    _replaceMessageHandler websocket.js:286
    _onInitialMessage websocket.js:271
    onmessage websocket.js:174
    _connect websocket.js:174
    connect connection.js:553
    connect index.js:111
    fetchRegistrationForm panel.js:203
    abortRegistration panel.js:325
    onConnectStatusChanged panel.js:225
    fetchRegistrationForm panel.js:203
    _changeConnectStatus connection.js:1156
    _doDisconnect connection.js:1198
    _checkStreamError websocket.js:127
    _onMessage websocket.js:491
    onmessage websocket.js:286```

**Comment by jcbrand** [comment] 2024-12-20 06:49
Duplicate of #3386

**Closed by jcbrand** 2024-12-20 06:49 UTC
