### ISSUE TITLE
Nick Name not saving in chrome

### ISSUE THREAD

**Issue by fingertips-solutions** [conversejs/converse.js#1605] opened 2019-06-17 13:03 UTC
Hi,

I am trying to save profile data from chrome but it gives me this error. 

Sorry, an error happened while trying to save your profile data.

You can check your browser's developer console for any error output.

Its working on firefox though. 

can you help me here what can be the issue ? 

My converse is on one server and ejabberred is on another.

**Comment by jcbrand** [comment] 2019-06-17 13:26
How is this not a duplicate of #1596?

**Comment by fingertips-solutions** [comment] 2019-06-17 18:27
#1596 is not completed. how its working on one browser and does not on other one.

**Comment by jcbrand** [comment] 2019-06-17 19:16
I've already said in #1596 what I think the issue is, based on the information you provided.

**Closed** 2019-06-17 19:15 UTC
