### ISSUE TITLE
Chat highlight behaves odd

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse.js#2816] opened 2022-02-15 12:47 UTC
HEAD (b44e1c82f08502d5deb047457349bf1e37a803de) self-build, Firefox Stable

Highlight does not change to correct contact
![selectionoff](https://user-images.githubusercontent.com/2282799/154064171-a8e37c7e-63f9-4f96-b6f4-c9825630faba.jpg)

But, if I open a group it highlights that group or disappears when I switch away to a chat. Selecti the group again....highlighted...select 1:1 chat... nothing highlighted.

**Comment by RoyTheJet** [comment] 2022-05-11 20:36
Hey, would love to take a crack at this if that is all right?

**Comment by jcbrand** [comment] 2022-05-13 07:42
Hey @RoyTheJet, that would be great thanks. Have you been able to reproduce the issue? If you're unsure how to start or need help, let me know.

**Comment by RoyTheJet** [comment] 2022-05-14 19:55
Hey, @jcbrand I have not been able to reproduce the issue. Any help would be greatly appreciated thanks.

**Comment by jcbrand** [comment] 2022-05-17 19:42
@licaon-kter Can you still reproduce this bug?

**Comment by kicken** [comment] 2022-05-17 23:23
I encounter this issue still.   Seems to happen fairly reliably then closing out with a 1:1 chat open.  When logging in again it re-opens the chat and highlights that entry which then remains highlighted.  Problem does not seem to happen when a MUC or no chat was open when last closed out.

**Comment by licaon-kter** [comment] 2022-05-18 07:38
@jcbrand Yup, same for 858a6051accc9bbb4b30a0ad7505240a6a9d2c0e

Login, see an 1:1 being opened, click on another 1:1, see picture above

**Comment by RoyTheJet** [comment] 2022-05-18 22:11
Ok, I've reproduced this bug. I also have noticed, that if you have 1:1 chats in different groups collapsing the group with the **wrong** highlight will shift the highlight to the correct chat. Also, if you have chats in the same group collapsing, then reopening the group, will shift the highlight to the correct chat. I did this with the console open, it shows that the class attribute "open" does not shift to the correct "li" when being clicked.

**Comment by licaon-kter** [comment] 2022-05-19 03:42
Interesting, it is true that as the picture shows, that (wrongly) highlighted 1:1 is in a different group _(one named as `empty` or `space` but that's like a different issue :) )_

**Comment by m1sraapurva** [comment] 2022-09-08 11:23
Hi All!
As I was trying to write a plugin for modifying the behavior of roster items, I found something peculiar that I believe has to do with this issue:
please refer to converse.js/src/plugins/rosterview/contactview.js
method: ```
        initialize () {
        this.listenTo(this.model, "change", () => this.requestUpdate());
        this.listenTo(this.model, "highlight", () => this.requestUpdate());
        this.listenTo(this.model, 'vcard:add', () => this.requestUpdate());
        this.listenTo(this.model, 'vcard:change', () => this.requestUpdate());
//        console.log('this:', this);
    }```
when I added some prints to see "this" object and inspect what it was configured to listen to, I discovered that 
whenever the contacts are loaded from the cache, (i.e. a login without clearing cache and data), the RosterContact
elements are listening to events on different models than their own.
![problem](https://user-images.githubusercontent.com/16498568/189108525-bb24951e-7b2a-4dde-a6da-0c32119f030b.png)
As can be seen in the screenshot, the model of <converse-roster-contact> is different from what it is _listeningTo.
So it seems a possible cause of unrelated roster items being highlighted on click as for contact A. contact B's model is being listened for the "highlight" event.
Thank you.

**Comment by jcbrand** [comment] 2022-12-13 09:08
Thanks a lot for the info @m1sraapurva, I think you might have found the issue. 

This is because of how `lit-html` works when rendering a list of items. It re-renders DOM nodes in-place, even when the order of the list has changed.. We don't want this for the roster, instead we want DOM nodes to be moved around to reflect the new ordering, otherwise a DOM node that had one `model` receives a different one upon re-render (just like you noticed).

The solution is to use the `repeat` directive.

https://lit.dev/docs/templates/lists/#when-to-use-map-or-repeat

**Comment by licaon-kter** [comment] 2022-12-13 12:43
I've built e63ba2075f565a952b3ae5eebcd21beda4fad836 and still odd:

![highlight3](https://user-images.githubusercontent.com/2282799/207320786-40272efd-bd5d-4bb1-a9ab-6b9ec0de7851.jpg)
![highlight4](https://user-images.githubusercontent.com/2282799/207320793-c212978f-5c86-4c71-93e2-ef0fb9895c8e.jpg)

Do I need to nuke my stored session browser data?

**Comment by jcbrand** [comment] 2022-12-13 14:40
No, I'll check again.

**Closed** 2022-12-20 17:08 UTC
Labels: good first issue
