### ISSUE TITLE
XEP-0402: Bookmarks 2

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#2586] opened 2021-07-31 12:18 UTC
**Is your feature request related to a problem? Please describe.**
The current bookmarks situation is a mess, starting with [Bookmarks](https://xmpp.org/extensions/xep-0048.html) version 1.1 (published the 2007-11-07), which changed the storage mechanism from [Private XML](https://xmpp.org/extensions/xep-0049.html) to [PEP](https://xmpp.org/extensions/xep-0223.html) without any migration path. As a result, all clients (but Converse) stayed on the former, while Converse implements only the latter, resulting in the desynchronisation of the MUCs being joined by different clients. [Bookmarks Conversion](https://xmpp.org/extensions/xep-0411.html) was an attempt at fixing this mess, but it arrived after [Bookmarks 2](https://xmpp.org/extensions/xep-0402.html) which added (amongst other improvements) a third way to store bookmarks, as well as two optional features advertising synchronisation with the former two.

**Describe the solution you'd like**
Implement XEP-0402, but use it *only* when conversion from the former is advertised, otherwise it would introduce a third incompatible and unsynchronised storage. The ideal solution is described [at modernxmpp.org](https://docs.modernxmpp.org/client/groupchat/#bookmarks), but for compatibility with older Converse versions it might not be applicable right away.

**Describe alternatives you've considered**
Staying with the current situation, this requires every server admin to deploy [mod_bookmarks](https://modules.prosody.im/mod_bookmarks.html) (or similar) which we are deprecating from prosody-modules, as it is incompatible with [mod_bookmarks2](https://modules.prosody.im/mod_bookmarks2.html). Other clients (such as Movim) also started using XEP-0402 without any fallback, making themselves incompatible with any other client unless this mod_bookmarks2 is deployed.

Another “solution” would be to implement [XEP-0048 version 1.0](https://xmpp.org/extensions/attic/xep-0048-1.0.html), and to only use the current [XEP-0048 version 1.1](https://xmpp.org/extensions/xep-0048.html) when [XEP-0411](https://xmpp.org/extensions/xep-0411.html) isn’t advertised, bringing back compatibility with every other client, but that is also a regression compared to the current solution as there is no notification mechanism, and it is unlikely new servers will start deploying mod_bookmarks.

**Comment by licaon-kter** [comment] 2021-08-04 14:09
/duplicate of https://github.com/conversejs/converse.js/issues/1649 ?

**Comment by mwild1** [comment] 2021-08-05 11:33
Essentially a duplicate, yes, though it would be preferable to keep the detailed explanation of the issue that is in this one.

**Comment by linkmauve** [comment] 2024-06-10 14:52
Since this issue got written, Prosody 0.12 [shipped mod_bookmarks](https://prosody.im/doc/modules/mod_bookmarks) and Ejabberd 23.10 [added it to mod_private](https://www.process-one.net/blog/ejabberd-23-10/), so the two most widely used servers can now be configured to synchronise bookmarks between all three possible stores.

**Closed** 2024-12-21 03:57 UTC
Labels: Feature, XEP, Roster
