### ISSUE TITLE
Singleton mode doesn't work

### ISSUE THREAD

**Issue by Zash** [conversejs/converse.js#2647] opened 2021-09-13 20:47 UTC
**Describe the bug**
The [Prosody web chat](https://chat.prosody.im/) is using the embedded view mode

**To Reproduce**
1. Configure with both `singleton:true` and `view_mode:"embedded"`
2. ???
3. Blank page

Roug minimal config along these lines:

```js
converse.initialize({
"auto_join_rooms" : ["group@chat.example"],
"auto_login" : true,
"blacklisted_plugins" : [
	"converse-controlbox",
],
"bosh_service_url" : "/bosh",
"discover_connection_methods" : false,
"jid" : "anonymous.sasl.chat.example",
"singleton" : true,
"view_mode": "embedded"
});
```

Setting `singleton:false` (or commenting it out) makes it sorta work, but the single chat does not take up the entire viewport, leaving space roughly the size of the missing controlbox.

**More complete example** with HTML etc in the form of [an attempt to upgrade chat.prosody.im](https://chat.prosody.im/8em.html) to Converse.js 8.x

**Expected behavior**
Expected the [Prosody web chat](https://chat.prosody.im/) but with Converse.js 8.x goodies :)

**Screenshots**

Imagine a blank page.

**Environment (please complete the following information):**
 - Firefox 78 ESR (also tested on FF 91 earlier)
 - Converse.js v8.0.0

**Additional context**

**Comment by lunika** [comment] 2021-09-15 13:56
We have the same issue on [Marsha](https://github.com/openfun/marsha/).
The `converse-root` element exists in the DOM but we don't see it.
We also use the [root](https://conversejs.org/docs/html/configuration.html#root) configuration settings. It works but not like in version 7.

With the exact same config, you can see the difference between converse 8 and 7 : 

## Converse 7 

![Screenshot 2021-09-15 at 15-34-19 Screenshot](https://user-images.githubusercontent.com/767834/133446769-67c744eb-8d9b-48d6-831e-e028e0dd73d6.png)


## converse 8

![Screenshot 2021-09-15 at 15-24-26 Screenshot](https://user-images.githubusercontent.com/767834/133446805-2ec14ca6-f569-4d99-8cf2-f5ed9f15af7f.png)

**Comment by rscmbbng** [comment] 2021-09-24 08:59
Can confirm we have the same issue on a few webchats, all use the singleton option.

**Comment by jcbrand** [comment] 2021-09-24 09:54
I believe this should be fixed now. Let me know if there are still issues.

**Closed** 2021-09-24 09:53 UTC
Labels: bug, UI

**Comment by jcbrand** [comment] 2021-09-24 09:55
BTW, this fix contains breaking changes, so will only be able to go out in Converse 9 (which probably won't take as long to release like Converse 8).

For now you'll have to make the builds yourself if you want to use the latest code.

**Comment by JohnXLivingston** [comment] 2021-11-02 17:18
> BTW, this fix contains breaking changes, so will only be able to go out in Converse 9 (which probably won't take as long to release like Converse 8).
> 

Can you please add in the v8.0.0 and/or v8.0.1 release notes that singleton mode is broken?
I just lost 2 hours to find why upgrading to v8.0.1 brokes my application. I finally saw in the changelog for the upcoming v9 that there is a fix for the singleton mode... (and yes, that was my bug: it works with singleton set to false).

**Comment by JohnXLivingston** [comment] 2021-11-02 17:30
Looking at your commit https://github.com/conversejs/converse.js/commit/84c6a0039c78b6e1f1e6054ec9ee42586c45f600 , I see the following comment:
```
It's now necessary to add a `converse-root` element in the DOM where you
want Converse to render (previously it was any element with the id
`#conversejs`).
```

You have modified the demo/embedded.html to replace `<div id="conversejs"></div>` by `<converse-root></converse-root>`.

But the fullscreen.html file ( https://github.com/conversejs/converse.js/blob/master/fullscreen.html ) was not modified, and don't have the `converse-root` DOM element. It still uses `<div id="conversejs-bg"></div>`. It seems that this DOM id is still used here: https://github.com/conversejs/converse.js/blob/93e1758a0bdf96dd86d318c4e0525fd36a12f829/src/plugins/chatboxviews/view.js#L30

Is this correct?

What will be the correct way to have a singleton mode, in a fullscreen page? (for v9)

**Comment by jcbrand** [comment] 2021-11-03 16:21
@JohnXLivingston The text you quoted is specifically when you want to control where Converse gets embedded into the page (which generally would be when you've set `view_mode` to `embedded`).

For a fullscreen Converse, it's not necessary to do this because you don't need to control where in the DOM Converse gets embedded and Converse will insert itself (as `converse-root`).

The `<div id="conversejs-bg"></div>` is something else (it has a different `id` attribute) and is just to show a Converse styled background when there is no chat open in fullscreen mode.

**Comment by JohnXLivingston** [comment] 2021-11-03 16:29
> @JohnXLivingston The text you quoted is specifically when you want to control where Converse gets embedded into the DOM (which generally would be when you've set `view_mode` to `embedded`).
> 
> For a full page Converse (`view_mode` is `fullscreen`), it's not necessary to do this because you don't need to control where in the DOM Converse gets embedded and Converse will insert itself (as `converse-root`).
> 
> The `<div id="conversejs-bg"></div>` is something else (it has a different `id` attribute) and is just to show a Converse styled background when there is no chat open in fullscreen mode.

Thanks for your response!
Have you tested the singleton mode in fullscreen mode with your fix? (I can confirm that singleton mode is not working with v8.0.1).

**Comment by jcbrand** [comment] 2021-11-04 19:06
I think I did, but it's been a while back.

It's fairly easy to build Converse from the latest source (at least on Linux or Mac).

Just check out the repo and then run `make dist` and then the files necessary are in the dist folder.

It would help if more people did that and reported whether their issues are fixed.

**Comment by JohnXLivingston** [comment] 2021-11-05 20:08
I'll test it next week, and tell you if it is working.
Thanks.

**Comment by JohnXLivingston** [comment] 2021-11-08 10:46
With the current version in the git repository, I can confirm that singleton mode is working for fullscreen mode.

But, there is a styling problem. I'll open a new issue.

**Comment by lunika** [comment] 2021-11-18 14:23
Hi @jcbrand this bug seems here again. Tested with commit e347621dc and the doesn't appear at all like before.

**Comment by jcbrand** [comment] 2021-11-19 08:01
@lunika: Looks fine to me. You need to rebuild the distribution files via `make dist` whenever you update your repo.

**Comment by lunika** [comment] 2021-11-19 08:37
Yes this is what I made. I built converse using `make dist`. The chat doesn't appear at all in the browser. I see it in the DOM and if the `converse-chats` element is changed by a `div` then it appears.

**Comment by jcbrand** [comment] 2021-11-19 21:40
> if the converse-chats element is changed by a div then it appears.

This sentence doesn't make sense to me. What do you mean?

**Comment by lunika** [comment] 2021-11-19 21:54
When I inspect the DOM with the developer console in my browser, in the code generated by converse, a `<converse-chats />` element is added in the `<converse-root />` element.

**Comment by jcbrand** [comment] 2021-11-19 22:16
Perhaps you just need to add the `conversejs` class to `converse-root` or to its parent.
