### ISSUE TITLE
Display vcard data in roster items

### ISSUE THREAD

**Issue by bhattaxay** [conversejs/converse.js#1835] opened 2020-01-14 20:52 UTC
I have set the vcard data using [https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#set-vcard](ejabberd_set_vcard) this api. Like user PHOTO and URL in vcard. 

I also able to get that data by [https://docs.ejabberd.im/developer/ejabberd-api/admin-api/#get-vcard](ejabberd_get_vcard) this api.

But i am not able to get those vcard data in roster_item.html page. Let me know how this is possible in converse js.

**Comment by Echolon** [comment] 2021-04-02 22:04
I think this is a duplicate of https://github.com/conversejs/converse.js/issues/1130

**Comment by jcbrand** [comment] 2021-04-09 11:36
#1130 is per MUC, and this one is per user.

**Comment by jcbrand** [comment] 2024-06-10 07:07
This has been done long ago already.

**Closed by jcbrand** 2024-06-10 07:07 UTC
Labels: UX, UI, improvement
