### ISSUE TITLE
Avatar image profile not update

### ISSUE THREAD

**Issue by krot3232** [conversejs/converse.js#1608] opened 2019-06-18 11:04 UTC
When you first enter the chat or clear all caches avatar image is not installed from the vcard.
video https://drive.google.com/open?id=1bAasg2govVVtNJ8MxUo3p6DTPjW6SjSd

**Comment by jcbrand** [comment] 2019-06-18 11:27
Duplicate of #1455

**Closed by jcbrand** 2019-06-18 11:27 UTC
