### ISSUE TITLE
Cannot receive OMEMO messages from Gajim or ChatSecure

### ISSUE THREAD

**Issue by t2d** [conversejs/converse.js#1193] opened 2018-09-09 18:02 UTC
First, thank you for this great peace of software.
Second, I wanted to try the OMEMO encryption, so I integrated `libsignal` into `4.0.0` as told in https://github.com/conversejs/converse.js/issues/497#issuecomment-419606466.

The lock appears and I can send OMEMO encrypted messages. However, if I want to reply from another client, `conversejs`  is not showing anything. I only get 

> New remote ephemeral key 

from `libsignal` in debug. I tried with ChatSecure and Gajim.

**Comment by jcbrand** [comment] 2018-09-10 15:05
Thanks. I'm not sure what the issue is here.

I've tested OMEMO between Converse and Conversations.

**Comment by t2d** [comment] 2018-09-11 12:13
I don't have an Android device so I cannot verify if this is a client specific problem. But I ran into problems with different OMEMO implementations before.

**Comment by siikamiika** [comment] 2018-10-12 11:45
I ran into the same problem and intercepted two messages sent to my converse.js, one from  Gajim (doesn't work) and another from Conversations (works). Here are the messages, anonymized:

From Gajim (doesn't work):

```xml
<message xmlns="jabber:client" type="chat" to="ME/converse.js" from="ME">
  <received xmlns="urn:xmpp:carbons:2">
    <forwarded xmlns="urn:xmpp:forward:0">
      <message xmlns="jabber:client" type="chat" to="ME/Conversations" from="FRIEND/gajim" id="">
        <thread>...</thread>
        <request xmlns="urn:xmpp:receipts"/>
        <active xmlns="http://jabber.org/protocol/chatstates"/>
        <thread>...</thread>
        <origin-id xmlns="urn:xmpp:sid:0" id=""/>
        <encrypted xmlns="eu.siacs.conversations.axolotl">
            ...
        </encrypted>
        <encryption xmlns="urn:xmpp:eme:0" name="OMEMO" namespace="eu.siacs.conversations.axolotl"/>
        <store xmlns="urn:xmpp:hints"/>
      </message>
    </forwarded>
  </received>
</message>

```

from Conversations (works):

```xml
<message xmlns="jabber:client" type="chat" to="ME/converse.js" from="ME">
  <received xmlns="urn:xmpp:carbons:2">
    <forwarded xmlns="urn:xmpp:forward:0">
      <message xmlns="jabber:client" type="chat" to="ME" from="FRIEND/Conversations" id="">
        <body>I sent you an OMEMO encrypted message but your client doesn&#x2019;t seem to support that. Find more information on https://conversations.im/omemo</body>
        <encrypted xmlns="eu.siacs.conversations.axolotl">
            ...
        </encrypted>
        <request xmlns="urn:xmpp:receipts"/>
        <markable xmlns="urn:xmpp:chat-markers:0"/>
        <origin-id xmlns="urn:xmpp:sid:0" id=""/>
        <store xmlns="urn:xmpp:hints"/>
        <encryption xmlns="urn:xmpp:eme:0" name="OMEMO" namespace="eu.siacs.conversations.axolotl"/>
      </message>
    </forwarded>
  </received>
</message>
```

I don't know how converse.js works, but the message that doesn't work seems to be missing `<body>`, and I guess that could be the reason why the message isn't shown. In both messages, the structure of `<encrypted>` is identical.

**Comment by siikamiika** [comment] 2018-10-13 08:09
I just confirmed that OMEMO encrypted messages work from Gajim to converse.js again if I add this to Gajim's OMEMO plugin:

```diff
diff --git a/omemo/omemo_connection.py b/omemo/omemo_connection.py
index c1cbf52..6ce0baa 100644
--- a/omemo/omemo_connection.py
+++ b/omemo/omemo_connection.py
@@ -546,6 +546,9 @@ class OMEMOConnection:
                     error=error, time_=time.time(), session=event.session))
             return
 
+        body = Node('body', payload='asdf')
+        event.msg_iq.addChild(node=body)
+
         encrypted_node = OmemoMessage(msg_dict)
         event.msg_iq.addChild(node=encrypted_node)

```

Not sure who's not following the spec, but at least this could be fixed in either client and Gajim isn't the only client with this problem.

**Comment by jcbrand** [comment] 2018-10-13 08:12
@siikamiika Excellent work, thanks for drilling down to find the problem.

According to [XEP-0384](https://xmpp.org/extensions/xep-0384.html), the `<payload>` corresponds to the message's `<body>`, so I think it should be fine for a message to not have a `<body>` tag.

I'll fix asap.

**Closed** 2018-10-15 21:47 UTC
Labels: bug
