### ISSUE TITLE
div.list-container.roster-contacts causes the last few contacts to be permanently invisible

### ISSUE THREAD

**Issue by andrei-pmbcn** [conversejs/converse.js#1506] opened 2019-03-22 11:21 UTC
The contact list (div.list-container.roster-contacts) has its css height set to 100%. Its parent, div#converse-roster.controlbox-section, has its height set to calc(100% - 70px). Because of the fact that the contact's list height is 100%, when the contact list overflows, it extends to the bottom of the screen and its scrollbar thus fails to reach the last few of its contacts, making these contacts permanently unavailable. A solution is to set the height of the contact list to calc(100% - 70px) or inherit, which confines the list to the converse overlay and thus allows the last few contacts in the contact list to be visible.

I am using Chrome 73 and my sample contact list has roughly 40 people in it.

**Comment by jcbrand** [comment] 2019-05-21 10:13
Did you modify Converse in any way? I don't see this issue.

**Comment by jcbrand** [comment] 2019-10-02 09:49
Closing due to not being able to reproduce and not getting feedback.

**Closed** 2019-10-02 09:49 UTC
Labels: bug
