### ISSUE TITLE
Converse js stopped and not received messages after Tab Discarding by Browser

### ISSUE THREAD

**Issue by sky-dtu** [conversejs/converse.js#2853] opened 2022-03-16 16:46 UTC
**Describe the bug**
[Auto Tab Discarding](https://chrome.google.com/webstore/detail/disable-automatic-tab-dis/dnhngfnfolbmhgealdpolmhimnoliiok?hl=en) feature of latest browsers kills the tab in which Conversejs Chat Application is opened citing memory management when the user has opened multiple tabs. When the user switches back to Converse Chat Application Tab in the browser, the tab just reloads again and all the messages during that period were not received in real-time.

**To Reproduce**
1. Open your Converse Chat Application and login
2. Open multiple tabs and do your work
3. Switch back to the Converse Tab after around 40-50mins
4. You might see that your tab is being loaded again

**Expected behavior**
Being a real-time chat application, the messages should be notified immediately. But due to this Tab Discarding, the user needs to click back to that Tab and reload to see the new messages.

**Environment**
 - Desktop and Mobile
 - Browser - Chrome, Edge, Firefox
 - Converse.js version [9.0.0]

**Additional context**
This issue will not appear immediately. You have to wait to get that tab discarded by the browser.

**Configuration Settings**

```
    converse.initialize({
        
        bosh_service_url: 'https://subdomain.domain.com:0000/http-bind/', 
        view_mode: 'fullscreen',
        persistent_store : indexedDB,
        authentication: 'login',
        auto_login: true,
        auto_reconnect: true,
        keepalive: true,
        debug: true,

        jid: some_jid,
        password: some_password,

        play_sounds: true,
        show_desktop_notifications: true
    }
```

**Comment by jcbrand** [comment] 2022-03-18 09:33
I think this can be solved by (and is therefore a duplicate of) #1519

**Closed** 2022-03-21 17:53 UTC
Labels: duplicate
