### ISSUE TITLE
Uncaught (in promise) null

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1745] opened 2019-10-08 13:46 UTC
Logged by Converse 5.0.4:

```Uncaught (in promise) null
(anonymous) @ core.js:2145
run @ core.js:1370
_onIdle @ core.js:3193
(anonymous) @ core.js:3207
setTimeout (async)
_onIdle @ core.js:3207
(anonymous) @ core.js:3207
setTimeout (async)
_onIdle @ core.js:3207
(anonymous) @ core.js:3207
setTimeout (async)
```

![image](https://user-images.githubusercontent.com/4253898/66400902-9993ed00-e9e2-11e9-8bcb-ac428b60a3a8.png)

![image](https://user-images.githubusercontent.com/4253898/66400699-4326ae80-e9e2-11e9-905c-983d916173f7.png)

**Comment by jcbrand** [comment] 2019-10-08 13:51
@guusdk Can you see for which stanzas this timeout was? I assume it's related to IQ stanzas. The code you link to looks like it's in Strophe.js which is too low-level and doesn't tell me where it should be fixed.

**Comment by guusdk** [comment] 2019-10-08 14:02
I'm unsure how I can correlate that error to one of the many stanzas flying around.

Maybe a good improvement is to log more info, when this error occurs. Something like a stanza ID maybe.

I just had something similar, but different, which appears to relate to service discover:

![image](https://user-images.githubusercontent.com/4253898/66402329-f42e4880-e9e4-11e9-8806-190500e8dfd3.png)

**Comment by jcbrand** [comment] 2019-10-08 14:04
You can put a breakpoint there where the error happens. If it happens again you can look at the call stack and find what the cause was.

With the information at hand I'm not sure I can fix anything.

**Comment by guusdk** [comment] 2019-10-08 14:12
Okay, I got something, but I'm not sure how to get more info from this?

![image](https://user-images.githubusercontent.com/4253898/66403206-78350000-e9e6-11e9-9def-ee6133e0800d.png)

**Comment by jcbrand** [comment] 2019-10-08 15:33
If you type the relevant variable name in the console, then you usually get a better printout if it's an XML element, you then see the element's markup which will tell you exactly what kind of stanza it is and how it looks.

**Comment by jcbrand** [comment] 2019-11-09 11:05
Looking at the information at hand... an IQ stanza timed out (in which case Strophe returns `null` instead of a stanza or Error) and this happened during some kind of service discovery query.

The code that was doing the service discovery wasn't prepared for a timeout (i.e. receiving `null`), hence the error.

I however don't know which code this is and it's not clear from the info provided.

**Closed** 2020-10-19 08:10 UTC
Labels: Not enough info
