### ISSUE TITLE
cannot resize the controlbox

### ISSUE THREAD

**Issue by joudinet** [conversejs/converse.js#3545] opened 2024-11-15 10:18 UTC
**Describe the bug**
When trying to resize the controlbox in both fullscreen and embedded view_mode, nothing happen. I do see the cursor changing to w-resize but the resizing doesn't work. On the contrary, resizing the participant list works.

**To Reproduce**
1. Set view_mode to either fullscreen or embedded.
2.  Log in and try to resize the control box horizontally.

**Expected behavior**
The control box width should adapt to the resizing movement.

**Environment (please complete the following information):**
 - Desktop
 - Browser Firefox 132
 - Converse.js version 10.1.7

**Additional context**
I've also tested it on converse.js master version and the same issue appears.

**Comment by jcbrand** [comment] 2024-11-21 07:18
The controlbox has never been resizable, so this is more a feature request than a bug report, although people get confused because the mouse pointer changes to make it look like it's resizable.

**Comment by joudinet** [comment] 2024-11-21 11:06
I guess the issue is then to have a `<div class="dragresize dragresize-left"></div>` element inside the `converse-muc` element, if it is not resizable?
As a workaround, I put a `display: none` to this element so the cursor does not change to `w-resize`. Thanks.

**Comment by jcbrand** [comment] 2024-12-26 06:21
Looks like the mouse pointer no longer shows. Closing as duplicate of #2692

**Closed by jcbrand** 2024-12-26 06:21 UTC
