### ISSUE TITLE
Unable send encrypted OMEMO: Invalid signature  libsignal-protocol.js Converse v5.0.3

### ISSUE THREAD

**Issue by danjde** [conversejs/converse.js#1729] opened 2019-09-24 08:21 UTC
Hi Devs,
I've just installed (from git) on VPS Debian Stretch, Prosody 0.11, Fail2ban 0.9.6-2, Shorewall 5.0.15.6-1, Apache 2.4.25-3, modsecurity 3.0.0-3, php7 7.0.33, Converse.js v5.0.3.

Then I've enabled OMEMO, as described from @licaon-kter [here,](https://github.com/conversejs/converse.js/issues/1245#issuecomment-480012668)
the green padlock is present but trying to send in OMEMO mode I get the following error:

```
Unable to send an encrypted message due to an unexpected error.

<iq xmlns="jabber:client" to="cosmogonia@3x1t.org/converse.js-52759909" type="error" id="0afd7887-a4e6-4d06-831c-54a6eb8f0473:sendIQ"><error type="cancel"><item-not-found xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>

```
and

```
JQMIGRATE: Migrate is installed, version 1.4.1  jquery-migrate.min.js:2:542
Successfully compiled asm.js code (total compilation time 88ms; caching disabled in Firefox ESR52)  libsignal-protocol.js
pre-main prep time: 12 ms  libsignal-protocol.js:136:7
Errore interpretazione XML: errore di sintassi
Indirizzo: https://www.converse.3x1t.org/fullscreen.html
Riga numero 1, colonna 1:  fullscreen.html:1:1
Error: attemptNonPreboundSession: Could not find any credentials to log you in with!  converse.min.js:144:14262
 ERROR: Error while fetching bookmarks  converse.min.js:144:12666
	Pe.log https://cdn.conversejs.org/5.0.3/dist/converse.min.js:144:12666
	onBookmarksReceivedError https://cdn.conversejs.org/5.0.3/dist/converse.min.js:146:55735
	fetchBookmarksFromServer/< https://cdn.conversejs.org/5.0.3/dist/converse.min.js:146:54994
 ERROR: Could not build an OMEMO session for device 8076  converse.min.js:144:12666
	Pe.log https://cdn.conversejs.org/5.0.3/dist/converse.min.js:144:12666
	a https://cdn.conversejs.org/5.0.3/dist/converse.min.js:152:156229
 ERROR: Internal.curve25519_async.verify/<@https://www.converse.3x1t.org/3rdparty/libsignal-protocol-javascript/dist/libsignal-protocol.js:25278:28
Internal.curve25519_async.verify@https://www.converse.3x1t.org/3rdparty/libsignal-protocol-javascript/dist/libsignal-protocol.js:25276:20
wrapCurve25519/<.Ed25519Verify@https://www.converse.3x1t.org/3rdparty/libsignal-protocol-javascript/dist/libsignal-protocol.js:35157:24
Internal.crypto.Ed25519Verify@https://www.converse.3x1t.org/3rdparty/libsignal-protocol-javascript/dist/libsignal-protocol.js:35268:20
SessionBuilder.prototype.processPreKey/</<@https://www.converse.3x1t.org/3rdparty/libsignal-protocol-javascript/dist/libsignal-protocol.js:35804:16
  converse.min.js:144:12666
	Pe.log https://cdn.conversejs.org/5.0.3/dist/converse.min.js:144:12666
	a https://cdn.conversejs.org/5.0.3/dist/converse.min.js:152:156321
Error: Invalid signature  libsignal-protocol.js:25278:28
TypeError: invalid arguments
```

the message seems to start, but the recipient does not receive it.
I've try to exit, re-enter in untrusted device mode and back in trusted device as suggested [here](https://github.com/conversejs/converse.js/issues/1242) with no changes.

[Here](https://converse.3x1t.org/fullscreen.html) my Converse installation.

I've try from the official Converse.js web installation, the behavior is the same.

Thanks!

Davide

**Comment by licaon-kter** [comment] 2019-09-24 08:31
Can other clients use OMEMO? Eg. Dino or Conversations or Gajim?

**Comment by danjde** [comment] 2019-09-24 11:27
Yes, we are using many Jabber Clients (winfows, Linux and Android), all OMEMO enabled and working fine.
If you have any idea about, you can suggest me any test/checks.

Thanks!

Davide

**Comment by licaon-kter** [comment] 2019-09-24 11:59
This is a duplicate of https://github.com/conversejs/converse.js/issues/1524 ?

Can you try to host all the older files too, instead of using the CDN?

**Comment by danjde** [comment] 2019-09-24 12:02
> This is a duplicate of #1524 ?

No, #1524 was about Converse.js v4.2.0.

**Comment by danjde** [comment] 2019-09-24 12:06
> Can you try to host all the older files too, instead of using the CDN?

could you be clearer? I'm not exactly sure what you mean.

**Closed** 2019-09-24 12:09 UTC
