### ISSUE TITLE
Converse 4.0.4 embedded: shows `chatbox-navback` arrow in header

### ISSUE THREAD

**Issue by ge0rg** [conversejs/converse.js#1296] opened 2018-11-02 11:34 UTC
On mobile Chrome and Firefox, the `embedded` view will render a navback arrow in the top left corner:

![image](https://user-images.githubusercontent.com/165635/47913200-83f57980-de9b-11e8-9f0e-5c6270fd7d9e.png)

**Comment by ge0rg** [comment] 2018-11-02 12:07
Workaround:

```css
.chatbox-navback{display:none!important}
```

**Comment by dpw1** [comment] 2019-04-15 23:45
Is this bug still active? I could not reproduce it on Mobile Chrome (latest version) for Android.

**Comment by jcbrand** [comment] 2019-04-16 11:03
Did you test the "embedded" view mode?

Looking at the code, it doesn't look like it was fixed, but I pushed a fix now.

**Closed** 2019-04-16 11:02 UTC
Labels: UI, bug, good first issue, mobile
