### ISSUE TITLE
Problem when changing view_mode

### ISSUE THREAD

**Issue by fabiomontefuscolo** [conversejs/converse.js#1374] opened 2018-12-10 22:32 UTC
Hi, 

I'm having a problem when changing view_mode on ConverseJS. To reproduce, you have to be always in the same tab or you should use ConverseJS with trusted=true. Steps:

1. Login on ConverseJS;
2. Go to a page where ConverseJS is in overlayed mode and controlbox is on;
3. Go to a page where ConverseJS is in embedded mode and set up to auto join a specific room;

On step 3, the chat box will no appear. But if you inspect sessionStorage and delete a property which name format is "converse.chatbox-{{ jid }}-controlbox", the chatbox will appears normally after page reload.

That is it;

**Comment by fabiomontefuscolo** [comment] 2018-12-11 01:19
I think you can't blacklist converse-controlbox, even on embedded mode. Otherwise, ConverseJS will give controlbox data from sessionStorage to converse-chatbox. After some steps, ConverseJS will try to get VCard from this data and an error will be thrown.

**Comment by jcbrand** [comment] 2018-12-12 16:49
Yes, the problem appears to be that the controlbox is stored in sessionStorage while in overlayed mode and then loaded in embedded mode (which isn't equipped to deal with the controlbox and assumes it'll never be there).

I'm currently working on a proper solution for this and I think it'll have to be based on the [embedded-full](https://github.com/conversejs/converse.js/commit/54deb0ce4a442d4d0772d546495a33230a4486c6) branch which adds a new configuration option called [singleton](https://github.com/conversejs/converse.js/blob/embedded-full/docs/source/configuration.rst#singleton).

**Comment by jcbrand** [comment] 2018-12-12 18:11
@fabiomontefuscolo I've committed two fixes for this issue. Could you test with the latest build whether this solves this particular problem for you?

**Comment by jcbrand** [comment] 2018-12-13 14:44
Based on out-of-band feedback, the patch appears to solve the problem.

**Closed by jcbrand** 2018-12-13 14:44 UTC
Labels: bug

**Comment by RyanSacks** [comment] 2021-11-12 17:39
@jcbrand
So how can I fix `view_mode: 'embedded'` not showing up in my `<div id="conversejs"></div>`?

**Comment by jcbrand** [comment] 2021-11-14 21:27
@RyanSacks: I think the issue is that you need to use `<converse-root></converse-root>` and not `<div id="conversejs"></div>`.

**Comment by RyanSacks** [comment] 2021-11-14 22:04
@jcbrand
No that didn't work:
When I inspect the html element, all I get is this, with some Font Awesome svg information.

<converse-root class="conversejs converse-undefined theme-undefined" id="conversejs">
        <converse-chats class="converse-chatboxes row no-gutters converse-undefined">
        
        
    </converse-chats>
        <div id="converse-modals" class="modals"></div>
        <converse-fontawesome>
    
    
 **SVG ICON INFO HERE**
</converse-fontawesome>
    </converse-root>
