### ISSUE TITLE
MUC OMEMO Receiving messages fails

### ISSUE THREAD

**Issue by mwlczk** [conversejs/converse.js#1647] opened 2019-07-13 07:56 UTC
**Describe the bug**
MUC OMEMO Messages can be sent and are decryptable and readeable by multiple (gajim, conversations, chatsecure, converse.js) other clients.
Every omemo-message content send by a different  client is not being displayed. converse.js-omemo-messages are being displayed though. 

**To Reproduce**
1. join an omemo-muc with other client types which are somehow capable of omemo.
2. send an omemo-message from another client
3. you see, there is message but no content.

**Expected behavior**
I would expoect to see the message contents

**Environment (please complete the following information):**
 - Ubuntu 19.04
 - Browser Firefox 68
 - Converse.js version [https://github.com/conversejs/converse.js/commit/2fca442f57f64d1f0b174db21d879c170b866168]

**console output**
ERROR: Error No record for device someacc@conference.some.server/somedevice.123456789 converse.min.js:149:11605
    log https://some.server/converse.min.js:149
    reportDecryptionError https://some.server/converse.min.js:158
    decrypt https://some.server/converse.min.js:158
Error: No record for device someacc@conference.some.server/somedevice.123456789 libsignal-protocol.min.js:1:867980

**Comment by jcbrand** [comment] 2019-07-13 08:05
This is a duplicate of #1481

**Closed by jcbrand** 2019-07-13 08:05 UTC
