### ISSUE TITLE
CSS refers to webfonts through an absolute path.

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1747] opened 2019-10-08 13:52 UTC
`converse.css` and `converse.min.css` refer to the webfont location using an absolute path (under `/dist/webfonts/`

This makes it problematic to host Converse on a webserver in a context root other than one that is called 'dist'.

Please make the webfont location configurable or relative.

**Comment by joudinet** [comment] 2019-11-07 14:05
I tried to make this location depends on` __webpack_public_path__` variable instead of using the hardcoded /dist but I failed.
This is what I tried:
- update file-loader to version 4.2.0
- use the option postTransformPublicPath as described here:
https://github.com/webpack-contrib/file-loader#posttransformpublicpath

I've added the two following lines to webpack.common.js:
```
publicPath: 'webfonts/',
postTransformPublicPath: (p) => `__webpack_public_path__ + ${p}`
```
Unfortunately, make dist continues to generate a css file with hardcoded /dist in the webfont location :-(

**Comment by allo-** [comment] 2020-01-22 21:14
The issue is still present in 6.0.0 and I would like to use it with relative paths, too.

**Comment by jcbrand** [comment] 2020-01-23 07:50
I'm not sure what can/should be done to fix this.

Here's a relevant webpack issue: https://github.com/webpack-contrib/css-loader/issues/155

From that issue:

> To use a runtime public path:
> 
> You must not use the extract-text-webpack-plugin.
> You must set __webpack_public_path__ before referencing the stylesheets or images. (ES6 imports is moved to the top, be careful. Best use a extra file for setting the runtime path)

We already do that AFAICT, in [src/entry.js](https://github.com/conversejs/converse.js/blob/master/src/entry.js).

**Comment by jcbrand** [comment] 2020-02-13 09:20
As a workaround, you can build your own dist files and then specify the `ASSET_PATH` to be used for the webfonts.

Like this: `ASSET_PATH=https://example.org/dist/ make dist`

**Comment by jcbrand** [comment] 2020-02-13 11:33
I've made a fix to not rewrite `url()` paths in CSS. That means that assets are now loaded relative to the CSS file itself, which I believe resolves this issue.

**Comment by joudinet** [comment] 2020-02-19 10:37
Great, thanks. I'll test it when 7f69394 will be included in a release.

**Closed** 2021-11-25 09:49 UTC
Labels: improvement, build
