### ISSUE TITLE
_features failing on chrome under https

### ISSUE THREAD

**Issue by mreid0345** [conversejs/converse.js#1720] opened 2019-09-17 22:26 UTC
**Describe the bug**
Problem with n._features in /src/headless/converse-core.js
see screenshot

**Screenshots**
<img width="466" alt="error-09172019" src="https://user-images.githubusercontent.com/55162602/65084161-054ce200-d970-11e9-922a-689ed378bdbf.png">

**Environment (please complete the following information):**
 - Desktop or Mobile? both
 - Browser Chrome
 - Converse.js version 5.0.3

**Comment by mreid0345** [comment] 2019-09-17 22:35
converse.initialize({
        trusted: true,
        
        auto_away: 300,
        auto_reconnect: true,
        
        message_archiving: 'always',
        view_mode: 'fullscreen',
        
        
        
        allow_logout: true, // No point in logging out when we have auto_login as true.
            allow_muc_invitations: false, // Doesn't make sense to allow because only
                                          // roster contacts can be invited
            allow_contact_requests: false, // Contacts from other servers cannot,
                                           // be added and anonymous users don't
                                           // know one another's JIDs, so disabling.
            authentication: 'login',
 	    credentials_url: 'https://54.188.25.226/chat/chatjson.php',
            allow_contact_requests: true,
            auto_login: 'true',
            //auto_join_rooms: [
              //  'anonymous@conference.nomnom.im',
            //],
            //notify_all_room_messages: [
              //  'anonymous@conference.nomnom.im',
            //],
            bosh_service_url: 'https://54.188.25.226:5280/http-bind/', // Please use this connection manager only for testing purposes
            //jid: 'nomnom.im', // XMPP server which allows anonymous login (doesn't
                              // allow chatting with other XMPP servers).
            keepalive: false,
	    auto_reconnect: true,
	    debug: true,
            //hide_muc_server: true, // Federation is disabled, so no use in
                                   // showing the MUC server.
            play_sounds: true,
            show_controlbox_by_default: true,
            strict_plugin_dependencies: false,
            notification_icon: 'images/logo.svg',
            notification_delay: 5000,
            show_toolbar: true,
            show_desktop_notifications: true,
            visible_toolbar_buttons: {
                call: true,
                spoiler: true,
                emoji: true,
                toggle_occupants: true,
            },
            whitelisted_plugins: [
                'converse-bookmarks','converse-chatboxes', 'converse-chatview', 'converse-controlbox', 'converse-core', 'converse-disco', 'converse-dragresize', 'converse-fullscreen', 'converse-headline', 
                'converse-mam','converse-minimize','converse-muc','converse-muc-embedded','converse-notification','converse-ping','converse-profile','converse-register','converse-roomslist','converse-rosterview','converse-singleton','converse-spoilers'   
            ],
            show_send_button: false
    });

**Comment by mreid0345** [comment] 2019-09-17 22:37
converse.initialize({
        trusted: true,
        
        auto_away: 300,
        auto_reconnect: true,
        
        message_archiving: 'always',
        view_mode: 'fullscreen',
        
        
        
        allow_logout: true, // No point in logging out when we have auto_login as true.
            allow_muc_invitations: false, // Doesn't make sense to allow because only
                                          // roster contacts can be invited
            allow_contact_requests: false, // Contacts from other servers cannot,
                                           // be added and anonymous users don't
                                           // know one another's JIDs, so disabling.
            authentication: 'login',
 	    credentials_url: 'https://----------------------chatjson.php',
            allow_contact_requests: true,
            auto_login: 'true',
            bosh_service_url: 'https://54.188.25.226:5280/http-bind/', // Please use this connection manager only for testing purposes
            keepalive: false,
	    auto_reconnect: true,
	    debug: true,
           
            play_sounds: true,
            show_controlbox_by_default: true,
            strict_plugin_dependencies: false,
            notification_icon: 'images/logo.svg',
            notification_delay: 5000,
            show_toolbar: true,
            show_desktop_notifications: true,
            visible_toolbar_buttons: {
                call: true,
                spoiler: true,
                emoji: true,
                toggle_occupants: true,
            },
            whitelisted_plugins: [
                'converse-bookmarks','converse-chatboxes', 'converse-chatview', 'converse-controlbox', 'converse-core', 'converse-disco', 'converse-dragresize', 'converse-fullscreen', 'converse-headline', 
                'converse-mam','converse-minimize','converse-muc','converse-muc-embedded','converse-notification','converse-ping','converse-profile','converse-register','converse-roomslist','converse-rosterview','converse-singleton','converse-spoilers'   
            ],
            show_send_button: false
    });

**Comment by jcbrand** [comment] 2019-09-18 04:58
Duplicate of #1712

**Closed by jcbrand** 2019-09-18 04:58 UTC
