### ISSUE TITLE
Error after conversejs migration

### ISSUE THREAD

**Issue by PIWAL** [conversejs/converse.js#1756] opened 2019-10-11 11:00 UTC
I am using converse 3.3.4 an app that requires AMD javascript and require.js and everything works perfectly. So we have decided to migrated from 3.3.4 to 5.0.4 and we are getting one error.

xmpp sever: ejabberd 19
Linux server: ubunti 19.09
converjs 5.0.4

`<script src="https://cdn.conversejs.org/5.0.3/dist/converse.min.js" charset="utf-8"></script>`
I cannot use the above statement because the app I am using does not support .

Do here is how we are initializing converse.

```
require(['https://cdn.conversejs.org/5.0.4/dist/converse.js'],
function (converse) {});
require(['converse'], function (converse) {
        converse.initialize({
            bosh_service_url: 'https:/piwal.ca/http-bind/',
            keepalive: true,
            message_carbons: true,
            play_sounds: true,
            roster_groups: true,
            show_controlbox_by_default: true,
        });
    });
```
Here is the error I am getting

```
Error: Script error for "converse"
https://requirejs.org/docs/errors.html#scripterror
```
May be I am not doing the right thing.
So could someone help me ?

Regards,

**Comment by jcbrand** [comment] 2019-10-13 20:25
This is a duplicate of #1737 and #1743

**Closed by jcbrand** 2019-10-13 20:25 UTC

**Comment by jcbrand** [comment] 2019-10-13 20:45
@PIWAL:  You can try to change the webpack config of Converse.js to set [libraryTarget](https://webpack.js.org/configuration/output/#module-definition-systems) to `umd` or `amd` and then rebuild the dist files with `make dist`.

The resulting build should then probably be requirejs compatible.

Here's the patch:
```
diff --git a/webpack.prod.js b/webpack.prod.js
index a7e49f9e4..38a6bb2cb 100644
--- a/webpack.prod.js
+++ b/webpack.prod.js
@@ -12,6 +12,8 @@ module.exports = merge(common, {
     output: {
         publicPath: ASSET_PATH,
         filename: 'converse.min.js',
+        library: "converse",
+        libraryTarget: "umd"
     },
     plugins: [
         new MiniCssExtractPlugin({filename: '../dist/converse.min.css'}),
```

I thought about applying this patch but `converse.initialize` is not defined when you include converse.js via a script tag (it's available via `converse.default.initialize` but that's not acceptible).

Maybe there is a way to make this work, but I don't have the time to look into this. A pull request that adds AMD support to Converse.js without breaking other use-cases would be appreciated.

Alternatively, you can try to and configure Elgg so that require.js is informed that Converse.js is not an AMD-compatible library.

See here: http://learn.elgg.org/en/stable/guides/javascript.html#using-traditional-js-libraries-as-modules

Hope this helps.

**Comment by PIWAL** [comment] 2019-10-17 12:43
@jcbrand  thanks a lot for your help. 
But I have some errors when try to rebuild the dist files from converse.js source code.
Here are the errors I am getting.


`ERROR in ./sass/converse.scss (./node_modules/css-loader/dist/cjs.js??ref--9-1!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js??ref--9-3!./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--12-1!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js??ref--12-3!./sass/converse.scss)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, scandir '/home/pessek/Downloads/converse.js-5.0.4-/converse.js-5.0.4/node_modules/node-sass/vendor'
`
`ERROR in ./node_modules/@converse/headless/i18n.js
Module not found: Error: Can't resolve '../../locale' in '/home/pessek/Downloads/converse.js-5.0.4-/converse.js-5.0.4/node_modules/@converse/headless'`

`ERROR in ./node_modules/@converse/headless/converse-emoji.js
Module not found: Error: Can't resolve './emojis.json' in '/home/pessek/Downloads/converse.js-5.0.4-/converse.js-5.0.4/node_modules/@converse/headless'

`ERROR in ./node_modules/@converse/headless/templates/field.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
`
`ERROR in ./node_modules/@converse/headless/templates/vcard.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
`
`
ERROR in ./sass/converse.scss (./node_modules/css-loader/dist/cjs.js??ref--12-1!./node_modules/postcss-loader/src!./node_modules/sass-loader/dist/cjs.js??ref--12-3!./sass/converse.scss)
    Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    Error: ENOENT: no such file or directory, scandir '/home/pessek/Downloads/converse.js-5.0.4-/converse.js-5.0.4/node_modules/node-sass/vendor'

`

Regards,

**Comment by PIWAL** [comment] 2019-11-07 17:03
Thanks a lot @jcbrand .
I rebuild the dist files with `make dist` and conversejs works now. 
But `emojis.js` is not loading. What can I do for that ?

I am getting the following errors :
`Loading failed for the <script> with source “https://pessek-elggfinal32.com/dist/emojis.js”.`

Regards,
