### ISSUE TITLE
Merge MUC join and bookmark, leave and unset autojoin

### ISSUE THREAD

**Issue by linkmauve** [conversejs/converse.js#2623] opened 2021-09-04 09:36 UTC
**Is your feature request related to a problem? Please describe.**
Users get very confused when they leave a MUC and it “comes back” later, after they restarted their client. It’s also weird when you have to join a MUC every time, before you discover/understand the bookmarking mechanism. Until then, you also have no synchronisation with other clients you may use.

**Describe the solution you'd like**
Remove all mentions of bookmarks in the UI, and instead handle that as internal details of the protocol. Joining a MUC would automatically add a bookmark, leaving it would automatically set autojoin to false in the bookmark (but keep the bookmark so that it can be easily found again at a later point).

**Describe alternatives you've considered**
Keeping the UI as is is confusing to everyone but protocol nerds.

**Additional context**
Other clients like Conversations, Gajim, Dino or poezio (and perhaps other ones) already do so, with great UX success.

**Comment by licaon-kter** [comment] 2021-09-04 14:21
Duplicate of https://github.com/conversejs/converse.js/issues/1630 ?

**Closed** 2024-12-26 06:17 UTC
Labels: MUC
