### ISSUE TITLE
Modal problem with 5.x.x version

### ISSUE THREAD

**Issue by joweste** [conversejs/converse.js#1789] opened 2019-11-21 23:22 UTC
**Describe the bug**
I have used converse 3.3.4 because it is the latest version that works with my app.
I use adminlte as template, bootstrap 3  and viewmode is overlayed.

With converse.js starting with 5.x;x, when I click on converse gui to open a modal such as chat room info,for sample,  I am unable to close the  modal and the clicks on my app stops to  work.

**To Reproduce**
Open a modal of converse.js

**Expected behavior**
The modal doesn´t freeze the app.

**Environment (please complete the following information):**
 - Desktop
 - Browser Chrome
 - Converse.js version 5.x.x

**Comment by jcbrand** [comment] 2019-11-22 09:37
I'm closing this as a duplicate of #1448.

Sounds like a bootstrap overlay gets opened which sits on top of the other elements in the DOM, thereby preventing you from clicking on other elements.

**Closed by jcbrand** 2019-11-22 09:37 UTC
