### ISSUE TITLE
anything posted in MUC is posted twice / double posts

### ISSUE THREAD

**Issue by foss-** [conversejs/converse.js#1478] opened 2019-03-05 10:00 UTC
For me this is reproducible with Converse 4.1.2 in various implementations by posting any message to a MUC room.
(EDIT: not related to OMEMO use in MUCs here, msgs are unencrypted)

**Comment by jcbrand** [comment] 2019-03-05 16:52
I don't get duplicates, so you'll have to provide more information or a way to consistently reproduce the problem.

**Comment by Chobbes** [comment] 2019-03-11 02:37
@jcbrand this seems to happen to me with omemo.

![2019-03-10-223554_531x141_scrot](https://user-images.githubusercontent.com/5215874/54097107-04197780-4385-11e9-967b-dbfa748dd655.png)

Sending a message with OMEMO in a MUC gives you a, presumably duplicate, message which complains about OMEMO not working.

**Comment by jcbrand** [comment] 2019-03-11 09:29
Can you please check whether these problems still happen in the latest version of the master branch?

I made some fixes a few days ago

**Comment by Chobbes** [comment] 2019-03-11 13:12
@jcbrand pulled, rebuilt, and tried again. Issue still seems to be present. Worth noting, I have more than one device, so I have multiple OMEMO keys. That could be the issue, maybe?

**Comment by jjrh** [comment] 2019-03-11 15:45
I'm guessing this is related, or the same bug as https://github.com/conversejs/converse.js/issues/1483

**Comment by jcbrand** [comment] 2019-06-04 10:13
Should be fixed by now.

**Closed** 2019-06-04 10:13 UTC
