### ISSUE TITLE
Modal box is not working

### ISSUE THREAD

**Issue by mehwishIftikhar** [conversejs/converse.js#3226] opened 2023-07-10 08:07 UTC
Modal box is not working in it. When we click on "add contact button" then light blank screen is display. But when we inspect it then its modal code loaded successfully but nothing display. And i am also using bootsrap4.

My converse version is 10.0.0 and ejabberd version is 23.4.0. Can you guide me what i am missing.

Here is my converse intialization.

converse.initialize({
    bosh_service_url: 'https://domain.com:5443/bosh',
    auto_login: true,
    loglevel: 'debug',
    authentication: 'login',
    jid: 'name@domain.com',
    password: '1234',
    keepalive: true,
    //message_carbons: true,
    play_sounds: true,
    roster_groups: true,
    show_controlbox_by_default: true,
    allow_non_roster_messaging: true,
    // allow_muc: false,
    xhr_user_search: false,
    allow_logout: false,
    whitelisted_plugins: ['chatplugin'],
});

![converse_modal](https://github.com/conversejs/converse.js/assets/78149520/111df2ff-f6b1-4a61-b568-86b6eb833566)

**Comment by jcbrand** [comment] 2023-07-12 09:46
Duplicate of this issue? https://github.com/conversejs/converse.js/issues/2495

**Comment by iqra-ansari** [comment] 2023-07-14 10:35
const allmessages =  _converse.api.user.status.message.get(['test@ravi.store']); 
im using this code for fetching messages but show promise undefine errorr 
how can resolve it

**Closed** 2023-07-30 15:36 UTC
