### ISSUE TITLE
Shouldn't notify user upon receiving a message receipt.

### ISSUE THREAD

**Issue by guusdk** [conversejs/converse.js#1701] opened 2019-09-09 13:35 UTC
Using Converse.js 5.0.1, I suddenly received a batch or message receipts, like this one:

    <body xmlns='http://jabber.org/protocol/httpbind' ack='1919860478'><message to="guus.der.kinderen@example.org/converse.js-88020031" from="manasse.ngudia@example.com/converse.js-18059910" id="1718a40f-3f02-4b02-b9d1-49f6a70bf271" type="chat" xmlns="jabber:client"><received xmlns="urn:xmpp:receipts" id="28ab427d-b49f-4c13-9c19-633af6abaee4"></received><store xmlns="urn:xmpp:hints"></store></message></body>

My browser pinged for every single one of them.

**Comment by jcbrand** [comment] 2019-10-02 09:54
I think this is a duplicate of #1714 (or, rather the other way around) and it's been fixed in #1730).

**Closed by jcbrand** 2019-10-02 09:54 UTC
Labels: UX, bug, take-home assignment
