### ISSUE TITLE
OMEMO Group Chat Problem

### ISSUE THREAD

**Issue by MamasLT** [conversejs/converse.js#1686] opened 2019-08-21 01:56 UTC
**Describe the bug**
Have created a new private group chat with Conversations App, then via OpenFire Admin panel added another Member at the Permissions panel, so it would be able to connect to that chat. In Converse that member got invitation straight away. Opened new Group chat, pressed encryption keylock and sent few messages.
Now the problem is that all messages are shown as encrypted OMEMO messages, but only Converastions app on my phone are able to see all of them. The Converse DOES NOT show the actual message from phone user, only that something was sent, and also shows the lock, meaning its encrypted OMEMO.
This happened already few times with channels that were created via OpenFire itself.
Please investigate.

**Expected behavior**
Expected to see all OMEMO encrypted messages on both clients.

**Screenshots**
Adding screenshot
![converseproblem](https://user-images.githubusercontent.com/54340230/63396420-ea15a380-c3be-11e9-9e20-9a09a1fe7d42.jpg)

**Environment (please complete the following information):**
 - Desktop iMac, newest Mojave 10.14.6
 - Browser Firefox
 - Converse.js version 5.0.1
And Mobile with newest Conversations App (Xiami Redmi 6A)

**Comment by jcbrand** [comment] 2019-08-21 08:00
Closing because this is most likely a duplicate of #1481

**Closed by jcbrand** 2019-08-21 08:00 UTC
